
variables:
  DOCKER_REGISTRY: 112437402463.dkr.ecr.us-east-2.amazonaws.com
  AWS_DEFAULT_REGION: us-east-2
  APP_NAME: lambda-mlops-model
  DOCKER_HOST: tcp://docker:2375




variables:
  WORKON_HOME: .pipenv/venvs
  PIP_CACHE_DIR: .pipenv/pipcache

cache:
  key: pipenv
  paths:
    - .pipenv

on-pull-requests:
  image: "python:3.7"
  stage: test
  script:
    - pip install pylint
    - pip install pipenv
    - pipenv install
    - pipenv run pip freeze > requirements.txt
    - pipenv run pip freeze
    - pip install -r requirements.txt
    - pylint -d C0103 --fail-under=8 app

publish:
  stage: deploy
  only:
    - main
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    #- docker build -t $DOCKER_REGISTRY/$APP_NAME:latest . 
    - docker build -t 112437402463.dkr.ecr.us-east-2.amazonaws.com/dev/lambda-mlops-model:latest . 
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
